/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.23
 * Generated at: 2017-10-19 14:51:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import it.dstech.models.Contact;

public final class listacontatti_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/Lenovo8-7/Documents/workspace-sts-3.9.1.RELEASE/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/rubricaClient/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153377882000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1506678473729L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("it.dstech.models.Contact");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("    \n");
      out.write("    \n");
      out.write("    \n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css\" integrity=\"sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M\" crossorigin=\"anonymous\">\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.2.1.slim.min.js\" integrity=\"sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN\" crossorigin=\"anonymous\"></script>\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js\" integrity=\"sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4\" crossorigin=\"anonymous\"></script>\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js\" integrity=\"sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1\" crossorigin=\"anonymous\"></script>\n");
      out.write("<link href=\"../css/bootstrap2.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\n");
      out.write("  <script src=\"../js/jquery-3.2.1.js\"></script>\n");
      out.write("<script src=\"../js/bootstrap.js\"></script>\n");
      out.write("<script src=\"../js/bootstrap-confirmation.js\"></script>\n");
      out.write("<style type=\"text/css\">\n");
      out.write("table{\n");
      out.write("border:2px solid rgb(0,191,255);\n");
      out.write("}\n");
      out.write("td, th{\n");
      out.write("padding:2px 10px 2px 10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("tr:hover {\n");
      out.write(" backgroundr:rgba(0, 191, 255, 0.9) !important;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("<script type=text/javascript>\n");
      out.write("function modifica(contactID, contactNome, contactTelefono, contactEmail){\n");
      out.write("    document.getElementById(\"ID\").value = contactID; \n");
      out.write("    document.getElementById(\"Nome\").value = contactNome;  \n");
      out.write("    document.getElementById(\"Telefono\").value = contactTelefono;\n");
      out.write("    document.getElementById(\"Email\").value = contactEmail;\n");
      out.write(" }\n");
      out.write("\n");
      out.write("\n");
      out.write("function conferma(){\n");
      out.write("if(!confirm('Eliminare il contatto?'))\n");
      out.write("return false;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("function sortTable(a) {\n");
      out.write("  var table, rows, switching, i, x, y, shouldSwitch;\n");
      out.write("  table = document.getElementById(\"myTable\");\n");
      out.write("  switching = true;\n");
      out.write("  /*Make a loop that will continue until\n");
      out.write("  no switching has been done:*/\n");
      out.write("  while (switching) {\n");
      out.write("    //start by saying: no switching is done:\n");
      out.write("    switching = false;\n");
      out.write("    rows = table.getElementsByTagName(\"TR\");\n");
      out.write("    /*Loop through all table rows (except the\n");
      out.write("    first, which contains table headers):*/\n");
      out.write("    for (i = 1; i < (rows.length - 1); i++) {\n");
      out.write("      //start by saying there should be no switching:\n");
      out.write("      shouldSwitch = false;\n");
      out.write("      /*Get the two elements you want to compare,\n");
      out.write("      one from current row and one from the next:*/\n");
      out.write("      x = rows[i].getElementsByTagName(\"TD\")[a];\n");
      out.write("      y = rows[i + 1].getElementsByTagName(\"TD\")[a];\n");
      out.write("      //check if the two rows should switch place:\n");
      out.write("      if (x.innerHTML.toLowerCase() > y.innerHTML.toLowerCase()) {\n");
      out.write("        //if so, mark as a switch and break the loop:\n");
      out.write("        shouldSwitch= true;\n");
      out.write("        break;\n");
      out.write("      }\n");
      out.write("    }\n");
      out.write("    if (shouldSwitch) {\n");
      out.write("      /*If a switch has been marked, make the switch\n");
      out.write("      and mark that a switch has been done:*/\n");
      out.write("      rows[i].parentNode.insertBefore(rows[i + 1], rows[i]);\n");
      out.write("      switching = true;\n");
      out.write("    }\n");
      out.write("  }\n");
      out.write("  rows = table.getElementsByTagName(\"TR\");\n");
      out.write("  for (i = 1; i < (rows.length); i++) {\n");
      out.write("\t  if(i%2==0)\n");
      out.write("\t\t  rows[i].style.background = \"rgba(0, 191, 255, 0.6)\";\n");
      out.write("\t  else\n");
      out.write("\t\t  rows[i].style.background = \"rgba(0, 191, 255, 0.2)\";\n");
      out.write("  }\n");
      out.write("}\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<!-- Modal -->\n");
      out.write("<div class=\"modal fade\" id=\"myModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\n");
      out.write("  <div class=\"modal-dialog\" role=\"document\">\n");
      out.write("    <div class=\"modal-content\">\n");
      out.write("      <div class=\"modal-header\">\n");
      out.write("        <h5 class=\"modal-title\" id=\"exampleModalLabel\">Nuovo Contatto</h5>\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("          <span aria-hidden=\"true\">&times;</span>\n");
      out.write("        </button>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"modal-body\">\n");
      out.write("        <form method=post action=save>\n");
      out.write("        \n");
      out.write("  <div class=\"input-group\">\n");
      out.write("    <span class=\"input-group-addon\"><i class=\"glyphicon glyphicon-user\"></i></span>\n");
      out.write("    <input id=\"email\" type=\"text\" class=\"form-control\" name=\"nome\" placeholder=\"Nome\">\n");
      out.write("  </div>\n");
      out.write("   <div class=\"input-group\">\n");
      out.write("    <span class=\"input-group-addon\"><i class=\"glyphicon glyphicon-earphone\"></i></span>\n");
      out.write("    <input id=\"email\" type=\"text\" class=\"form-control\" name=\"telefono\" placeholder=\"Telefono\">\n");
      out.write("  </div>\n");
      out.write("   <div class=\"input-group\">\n");
      out.write("    <span class=\"input-group-addon\"><i class=\"glyphicon glyphicon-envelope\"></i></span>\n");
      out.write("    <input id=\"email\" type=\"text\" class=\"form-control\" name=\"mail\" placeholder=\"Email\">\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("      </div>\n");
      out.write("      <div class=\"modal-footer\">\n");
      out.write("      <button type=\"submit\" class=\"btn btn-primary\">Aggiungi Contatto</button></form>\n");
      out.write("        <button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">Close</button>\n");
      out.write("        \n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class=\"modal fade\" id=\"modalModifica\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\n");
      out.write("  <div class=\"modal-dialog\" role=\"document\">\n");
      out.write("    <div class=\"modal-content\">\n");
      out.write("      <div class=\"modal-header\">\n");
      out.write("        <h5 class=\"modal-title\" id=\"exampleModalLabel\">Nuovo Contatto</h5>\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("          <span aria-hidden=\"true\">&times;</span>\n");
      out.write("        </button>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"modal-body\">\n");
      out.write("        <form method=post action=update>\n");
      out.write("        <input type=hidden name=ID id=ID value=0>\n");
      out.write("  <div class=\"input-group\">\n");
      out.write("    <span class=\"input-group-addon\"><i class=\"glyphicon glyphicon-user\"></i></span>\n");
      out.write("    <input id=\"Nome\" type=\"text\" class=\"form-control\" name=\"nome\" placeholder=\"Nome\">\n");
      out.write("  </div>\n");
      out.write("   <div class=\"input-group\">\n");
      out.write("    <span class=\"input-group-addon\"><i class=\"glyphicon glyphicon-earphone\"></i></span>\n");
      out.write("    <input id=\"Telefono\" type=\"text\" class=\"form-control\" name=\"telefono\" placeholder=\"Telefono\">\n");
      out.write("  </div>\n");
      out.write("   <div class=\"input-group\">\n");
      out.write("    <span class=\"input-group-addon\"><i class=\"glyphicon glyphicon-envelope\"></i></span>\n");
      out.write("    <input id=\"Email\" type=\"text\" class=\"form-control\" name=\"mail\" placeholder=\"Email\">\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("      </div>\n");
      out.write("      <div class=\"modal-footer\">\n");
      out.write("      <button type=\"submit\" class=\"btn btn-primary\">Modifica Contatto</button></form>\n");
      out.write("        <button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">Close</button>\n");
      out.write("        \n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"card card-container\" id=myTable>\n");
      out.write("<table width=100%>\n");
      out.write("<tr style=\"background-color: rgba(0, 191, 255, 0.8);\"><th>Nome<span onclick=\"sortTable(0)\" class=\"glyphicon glyphicon-download\"></span></th><th>Mail<span onclick=\"sortTable(1)\" class=\"glyphicon glyphicon-download\"></span></th><th>Telefono<span onclick=\"sortTable(2)\" class=\"glyphicon glyphicon-download\"></span></th><th></th><th></th></tr>\n");
  
List<Contact> list = (List<Contact>) request.getAttribute("contactLis");
int i = 1;
for(Contact contact : list) {
	String colore;
	if(i%2==0) colore="rgba(0, 191, 255, 0.6)";
	else colore="rgba(0, 191, 255, 0.2)";
	
    out.println("<tr style='background-color:"+colore+"'><td><span class='glyphicon glyphicon-user'></span> " + contact.getNome() + "</td><td><span class='glyphicon glyphicon-envelope'></span> " + contact.getMail() + "</td><td><span class='glyphicon glyphicon-earphone'></span> " + contact.getTelefono() + "</td><td align=right width=200px><div style='display:block'><form onsubmit='return conferma()' method=post action='delete'><input type=hidden name=idElimina value="+contact.getID()+"><button class='btn btn-danger' type=submit value=elimina><span class='glyphicon glyphicon-trash'></button></form></td><td><button  class='btn btn-success' data-toggle='modal' data-target='#modalModifica' href=# onclick=\"modifica('"+contact.getID()+"','"+contact.getNome()+"','"+contact.getTelefono()+"','"+contact.getMail()+"')\"><span class='glyphicon glyphicon-edit'></span></div></td></tr>");
	i++;
}

      out.write("\n");
      out.write("\n");
      out.write("</table>\n");
      out.write("<button type=\"button\" class=\"btn btn-info btn-lg\" data-toggle=\"modal\" data-target=\"#myModal\">Aggiungi nuovo contatto</button>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
